remove filesystem type
nextcloud/files_retention pull request #111
Opened 2021-02-19 13:33 UTC by sualko

this should not be needed and it prevents that the trash bin
app is guaranteed to be loaded before

fix #34

2021-02-23 17:37 UTC, nickvergessen requested changes
As per issue I think this is wrong. Maybe instead something needs fixing in the trashbin app or type dav needs adding or so, but removing file system sounds wrong

2021-02-23 17:43 UTC, sualko commented
@nickvergessen thanks for your feedback. Can you give me a definition of a filestyem app, so that I know this for further projects?

2021-03-02 09:19 UTC, nickvergessen commented
From my pov these are apps that need to be loaded when the filesystem is interacted with. But now that I write this, I think you are right. This app only runs stuff in a background job and does not need to be interacted with on file system interaction.

2021-04-14 09:07 UTC, rullzer approved these changes

2021-04-14 09:07 UTC, merged

2021-04-16 06:58 UTC, rullzer commented
/backport to stable21